force-app/main/default/objects/Product_information__c/Product_information__c.object-meta.xml
<CustomObject>
    <description>This object reflects the configuration of the product depending on the house country.</description>
    <label>Product information</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Product information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products infromation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_information__c/fields/Commission__c.field-meta.xml
<CustomField>
    <fullName>Commission__c</fullName>
    <description>List of available commission</description>
    <label>Commission</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Commission_types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_information__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>List of available countries</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Conutry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_information__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>List of available products</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_information__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Value to be applied to the product into a country per commission.</description>
    <label>Value</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Commission_types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cost per Calendar Month</fullName>
    </customValue>
    <customValue>
        <fullName>ATM Fee in other currencies</fullName>
    </customValue>
    <customValue>
        <fullName>Card Replacement Cost</fullName>
    </customValue>
    <description>List of cost and fees</description>
    <masterLabel>Commission types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Conutry.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <description>List of home countries available in the system.</description>
    <masterLabel>Conutry</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Product.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Metal</fullName>
    </customValue>
    <description>Product</description>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProductInformationSelectorTest.cls
@isTest
public with sharing class ProductInformationSelectorTest {

    @TestSetup
    static void makeData(){
        Product_Information__c newProductInformation = new Product_Information__c();
        newProductInformation.Product__c = 'Standard';
        newProductInformation.Country__c = 'DE';
        newProductInformation.Commission__c = 'Cost per Calendar Month';
        newProductInformation.value__c = '0';
        insert newProductInformation;
    }

    @isTest
    static void getIntanceTest(){
        ProductInformationSelectorI prodInfoSelector = ProductInformationSelector.getInstance();
        System.assert(prodInfoSelector instanceof ProductInformationSelector);
    }

    @isTest
    static void givenProductAndConutry_whenCallGetProductInformation_thenAListOfProductInformationIsReturned(){

        ProductInformationSelectorI prodInfoSelector = ProductInformationSelector.getInstance();
        List<Product_Information__c> listOfProducts = prodInfoSelector.getProductInformationListByProductAndCountry('Standard','DE');

        System.assertEquals(1, listOfProducts.size());
        System.assertEquals('Cost per Calendar Month', listOfProducts.get(0).Commission__c);

    }
}