force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>Country where the contact&apos;s home is located</description>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Product contracted by the contact.</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <description>List of home countries available in the system.</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Product.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Metal</fullName>
    </customValue>
    <description>Product</description>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContactSelectorTest.cls
@isTest
public with sharing class ContactSelectorTest {

    @isTest
    static void getIntanceTest(){
        ContactSelectorI contactSelector = ContactSelector.getInstance();
        System.assert(contactSelector instanceof ContactSelector);
    }

    @isTest
    static void givenUUID_whenCallGetContactByUUID_thenContactIsReturned(){

        Contact newContact = new Contact();
        newContact.LastName = 'Monzonis';
        newContact.Product__c = 'Standard';
        newContact.Home_Country__c = 'DE';
        newContact.UUID__c = 'UWHUDEIhiahiedu';
        insert newContact;

        ContactSelectorI contactSelector = ContactSelector.getInstance();
        Contact currentContact = contactSelector.getContactByInternalID('UWHUDEIhiahiedu');

        System.assertEquals('Standard', currentContact.Product__c);
    }

    @isTest
    static void givenContactId_whenCallGetContactByID_thenContactIsReturned(){

        Contact newContact = new Contact();
        newContact.LastName = 'Monzonis';
        newContact.Product__c = 'Standard';
        newContact.Home_Country__c = 'DE';
        newContact.UUID__c = 'UWHUDEIhiahiedu';
        insert newContact;

        ContactSelectorI contactSelector = ContactSelector.getInstance();
        Contact currentContact = contactSelector.getContactById(newContact.id);

        System.assertEquals('Standard', currentContact.Product__c);
    }
}