force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>Country where the contact&apos;s home is located</description>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Product contracted by the contact.</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product_information__c/Product_information__c.object-meta.xml
<CustomObject>
    <description>This object reflects the configuration of the product depending on the house country.</description>
    <label>Product information</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Product information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products infromation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_information__c/fields/Commission__c.field-meta.xml
<CustomField>
    <fullName>Commission__c</fullName>
    <description>List of available commission</description>
    <label>Commission</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Commission_types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_information__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>List of available countries</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Conutry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_information__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>List of available products</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_information__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Value to be applied to the product into a country per commission.</description>
    <label>Value</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Commission_types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cost per Calendar Month</fullName>
    </customValue>
    <customValue>
        <fullName>ATM Fee in other currencies</fullName>
    </customValue>
    <customValue>
        <fullName>Card Replacement Cost</fullName>
    </customValue>
    <description>List of cost and fees</description>
    <masterLabel>Commission types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Conutry.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <description>List of home countries available in the system.</description>
    <masterLabel>Conutry</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <description>List of home countries available in the system.</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Product.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Metal</fullName>
    </customValue>
    <description>Product</description>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/REST_ContactProductInformationTest.cls
@isTest
public with sharing class REST_ContactProductInformationTest {

    private static final String CONTACT_IDENTIFIER = 'UWHUDEIhiahiedu';

    @TestSetup
    static void makeData(){
        Product_Information__c newProductInformation = new Product_Information__c();
        newProductInformation.Product__c = 'Standard';
        newProductInformation.Country__c = 'DE';
        newProductInformation.Commission__c = 'Cost per Calendar Month';
        newProductInformation.value__c = '0';
        insert newProductInformation;

        Contact newContact = new Contact();
        newContact.LastName = 'Monzonis';
        newContact.Product__c = 'Standard';
        newContact.Home_Country__c = 'DE';
        newContact.UUID__c = CONTACT_IDENTIFIER;
        insert newContact;
    }

    @isTest
    public static void givenValidUUID_whenGetProductInformationIsCall_thenReturnProductInformation(){

        RestRequest request = new RestRequest();
        request.requestURI = '/contact/v0/*';
        request.params.put('UUID', CONTACT_IDENTIFIER);
        request.httpMethod = 'GET';

        RestContext.request = request;
        RestResponse response = new RestResponse();
        RestContext.response = response;

        Test.startTest();
        REST_ContactProductInformation.getProductInformation();
        Test.stopTest();

        REST_ContactProductInformation.ProductInformationWrapperList responseBody = (REST_ContactProductInformation.ProductInformationWrapperList) JSON.deserialize(response.responseBody.toString(), REST_ContactProductInformation.ProductInformationWrapperList.class);

        System.assertEquals(CONTACT_IDENTIFIER, responseBody.contactIdentifier);
        System.assertEquals('Cost per Calendar Month', responseBody.productInformationList.get(0).productType);
    }

    @isTest
    public static void givenNonParameter_whenGetProductInformationIsCall_thenReturnError(){
        RestRequest request = new RestRequest();
        request.requestURI = '/contact/v0/*';
        request.httpMethod = 'GET';

        RestContext.request = request;
        RestResponse response = new RestResponse();
        RestContext.response = response;

        Test.startTest();
        REST_ContactProductInformation.getProductInformation();
        Test.stopTest();

        System.assertEquals(400, response.statusCode);
    }

    @isTest
    public static void givenInvalidUUID_whenGetProductInformationIsCall_thenReturnError(){
        RestRequest request = new RestRequest();
        request.requestURI = '/contact/v0/*';
        request.params.put('UUID', 'non-exist');
        request.httpMethod = 'GET';

        RestContext.request = request;
        RestResponse response = new RestResponse();
        RestContext.response = response;

        Test.startTest();
        REST_ContactProductInformation.getProductInformation();
        Test.stopTest();

        System.assertEquals(404, response.statusCode);
    }
}