force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>Country where the contact&apos;s home is located</description>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Product contracted by the contact.</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_information__c/Product_information__c.object-meta.xml
<CustomObject>
    <description>This object reflects the configuration of the product depending on the house country.</description>
    <label>Product information</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Product information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products infromation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_information__c/fields/Commission__c.field-meta.xml
<CustomField>
    <fullName>Commission__c</fullName>
    <description>List of available commission</description>
    <label>Commission</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Commission_types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_information__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>List of available countries</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Conutry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_information__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>List of available products</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_information__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Value to be applied to the product into a country per commission.</description>
    <label>Value</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Commission_types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cost per Calendar Month</fullName>
    </customValue>
    <customValue>
        <fullName>ATM Fee in other currencies</fullName>
    </customValue>
    <customValue>
        <fullName>Card Replacement Cost</fullName>
    </customValue>
    <description>List of cost and fees</description>
    <masterLabel>Commission types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Conutry.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <description>List of home countries available in the system.</description>
    <masterLabel>Conutry</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <description>List of home countries available in the system.</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Product.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Metal</fullName>
    </customValue>
    <description>Product</description>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProductInformationSummayControllerTest.cls
@isTest
public class ProductInformationSummayControllerTest {

    @TestSetup
    static void makeData(){
        Product_Information__c newProductInformation = new Product_Information__c();
        newProductInformation.Product__c = 'Standard';
        newProductInformation.Country__c = 'DE';
        newProductInformation.Commission__c = 'Cost per Calendar Month';
        newProductInformation.value__c = '0';
        insert newProductInformation;
    }

    @isTest
    public static void givenCaseId_whenGetProductInformationIsCall_thenReturnListOfData(){

        Contact newContact = new Contact();
        newContact.LastName = 'Monzonis';
        newContact.Product__c = 'Standard';
        newContact.Home_Country__c = 'DE';
        insert newContact;

        Case newCase = new Case();
        newCase.status = 'New';
        newCase.origin = 'Email';
        newCase.ContactId = newContact.id;
        insert newCase;

        List<ProductInformationSummayController.ProductConfiguration> products = ProductInformationSummayController.getProductInformationByCase(newCase.Id);

        System.assertEquals(1, products.size());
        System.assertEquals('Cost per Calendar Month', products.get(0).commission);
        System.assertEquals('0', products.get(0).value);
    }

    @isTest
    public static void givenCaseId_whenGetProductInformationIsCallWithError_thenReturnException(){

        Contact newContact = new Contact();
        newContact.LastName = 'Monzonis';
        newContact.Product__c = 'Standard';
        newContact.Home_Country__c = 'DE';
        insert newContact;

        Case newCase = new Case();
        newCase.status = 'New';
        newCase.origin = 'Email';
        newCase.Contact = newContact;
        insert newCase;

        try{
            List<ProductInformationSummayController.ProductConfiguration> products = ProductInformationSummayController.getProductInformationByCase(newCase.Id);
        } catch(AuraHandledException ex){
            System.assertEquals('An error occurred while trying to obtain product information.', ex.getMessage());
        }
    }
}