force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>Country where the contact&apos;s home is located</description>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Product contracted by the contact.</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product_information__c/Product_information__c.object-meta.xml
<CustomObject>
    <description>This object reflects the configuration of the product depending on the house country.</description>
    <label>Product information</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Product information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products infromation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_information__c/fields/Commission__c.field-meta.xml
<CustomField>
    <fullName>Commission__c</fullName>
    <description>List of available commission</description>
    <label>Commission</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Commission_types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_information__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>List of available countries</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Conutry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_information__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>List of available products</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_information__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Value to be applied to the product into a country per commission.</description>
    <label>Value</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Commission_types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cost per Calendar Month</fullName>
    </customValue>
    <customValue>
        <fullName>ATM Fee in other currencies</fullName>
    </customValue>
    <customValue>
        <fullName>Card Replacement Cost</fullName>
    </customValue>
    <description>List of cost and fees</description>
    <masterLabel>Commission types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Conutry.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <description>List of home countries available in the system.</description>
    <masterLabel>Conutry</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <description>List of home countries available in the system.</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Product.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Metal</fullName>
    </customValue>
    <description>Product</description>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/REST_ContactProductInformation.cls
@RestResource(urlMapping='/contact/v0/*')
global without sharing class REST_ContactProductInformation {

    @TestVisible
    private static final String ERROR_MESSAGE = 'An error ocurred to get the contact information';
    @TestVisible
    private static final String ERROR_STATUS = 'Failure';

    @HttpGet
    webservice static void getProductInformation(){

        RestRequest request = RestContext.request;
        String contactIdentifier = request.params.get('UUID');

        RestResponse response = RestContext.response;
        response.addHeader('Content-Type', 'application/json');

        if(contactIdentifier != null &&
            !String.isEmpty(contactIdentifier)){
            //TODO: Try to add the selector layer.
            Contact currentContact = [SELECT Product__c, Home_Country__c FROM Contact WHERE UUID__c = :contactIdentifier];
            //TODO: Check if contact exist.
            List<Product_Information__c> productInfoList = [SELECT Commission__c, Value__c 
                                                            FROM Product_Information__c 
                                                            WHERE Country__c = :currentContact.Home_Country__c AND 
                                                            Product__c = :currentContact.Product__c];
            
            ProductInformationWrapperList productList = generateResponse(contactIdentifier, productInfoList);
            response.statusCode = 200;
            response.responseBody = Blob.valueOf(JSON.serialize(productList));
        } else {
            response.statusCode = 400;
            response.responseBody = Blob.valueOf(JSON.serialize(new Error(ERROR_STATUS, ERROR_MESSAGE)));

        }
    }

    private static ProductInformationWrapperList generateResponse(String contactIdentifier, List<Product_Information__c> productInfoList ){
        ProductInformationWrapperList result = new ProductInformationWrapperList();
        result.contactIdentifier = contactIdentifier;

        List<ProductInformationWrapper> piWrapperList = new List<ProductInformationWrapper>();
        for(Product_Information__c pic : productInfoList){
            piWrapperList.add(new ProductInformationWrapper(pic.Commission__c, pic.Value__c));
        }
        result.productInformationList = piWrapperList;
        return result;
    }

    public class Error{
        public String status;
        public String message;
        
        public Error(String status, String message){
            this.status = status;
            this.message = message;
        }
    }

    public class ProductInformationWrapperList{
        public String contactIdentifier;
        List<ProductInformationWrapper> productInformationList;
    }

    public class ProductInformationWrapper{
        public String productType;
        public String value;

        public ProductInformationWrapper(String productType, String value){
            this.productType = productType;
            this.value = value;
        }
    }
}